# Site
name: "Quốc Định"
description: "Sorfware Engineer"
meta_description: "Chia se kien thuc, hoc hoi, huong dan, cung tien bo"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

google_analytics: 'UA-46278016-1'
disqus: 'Quốc Định IT'
mailchimp-list: 'https://facebook.com/PhungQuocDinh'

# Authors
authors:
  quocdinhit:
    name: Quốc Định
    display_name: Quốc Định
    email: pqd1997@gmail.com
    web: https://www.quocdinhit.tk
    facebook:  https://facebook.com/PhungQuocDinh
    description: "MÁY TÍNH là cổ máy ngu ngốc, có thể làm được những điều thông minh - DEV là những người thông minh, có thể làm những việc vô cùng ngu ngốc."
  quocdinh:
    name: Quốc Định
    display_name: Quốc Định
    email: pqd1997@gmail.com
    web: https://www.quocdinhit.tk
    facebook: https://facebook.com/PhungQuocDinh
    description: "MÁY TÍNH là cổ máy ngu ngốc, có thể làm được những điều thông minh - DEV là những người thông minh, có thể làm những việc vô cùng ngu ngốc."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-category-pages
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge